# Generated by Django 3.2.4 on 2021-07-31 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_admin_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 16, 43, 52, 651268)),
        ),
    ]
