# Generated by Django 3.2.4 on 2021-08-01 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210801_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 12, 1, 19, 103755)),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 12, 1, 19, 103755)),
        ),
    ]
