# Generated by Django 4.0.6 on 2022-07-20 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210801_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 21, 6, 43, 983073)),
        ),
        migrations.AlterField(
            model_name='question',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 21, 6, 43, 983879)),
        ),
    ]
