# Generated by Django 4.0.6 on 2022-07-20 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_article_date_alter_question_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 21, 6, 51, 404980)),
        ),
        migrations.AlterField(
            model_name='question',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 21, 6, 51, 405785)),
        ),
    ]
