# Generated by Django 4.0.6 on 2022-09-22 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_article_date_alter_question_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 18, 24, 35, 664738)),
        ),
        migrations.AlterField(
            model_name='question',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 18, 24, 35, 664738)),
        ),
    ]
