# Generated by Django 4.1.3 on 2022-12-19 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_article_date_alter_question_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 20, 49, 8, 178680)),
        ),
        migrations.AlterField(
            model_name='question',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 20, 49, 8, 178680)),
        ),
    ]
